Update scipy version requirement to >=1.15.0
After installation with `pip install nvidia-physical-ai-av` on Ubuntu 24.04, I ran into this error:

```
module 'scipy.spatial.transform' has no attribute 'RigidTransform'
```

This reason is probably that `python3-scipy==1.11.4` released via apt is too old and version `1.15.0` or newer is required.